
import { Country } from './types';

export const TRANSLATIONS = {
  ar: {
    back: "العودة",
    next: "التالي",
    loading: "جاري استخراج البيانات الرسمية من الوزارة...",
    chooseLanguage: "اختر لغة الواجهة",
    chooseCountry: "اختر بلدك",
    chooseGrade: "السنة الدراسية الرسمية",
    chooseStream: "الشعبة أو التخصص المعتمد",
    chooseSubject: "المواد الدراسية المقررة",
    lessonsAndBooks: "الدروس والكتب",
    officialCurriculum: "المناهج الرسمية المعتمدة",
    examsAndAssessments: "الامتحانات والفروض",
    previousExams: "نماذج رسمية من سنوات سابقة",
    generateAssessment: "إنشاء فرض جديد (تفاعلي)",
    generateAssessmentDesc: "توليد فرض مخصص بناءً على دروسك",
    officialExams: "الامتحانات الرسمية",
    officialExamsDesc: "نماذج رسمية من سنوات سابقة (PDF)",
    writeLessons: "اكتب الدروس المعنية بالفرض",
    lessonsPlaceholder: "يمكنك كتابة اسم درس واحد أو عدة دروس مفصولة بفاصلة",
    exampleLessons: "مثال: الاشتقاق، الدالة الأسية، النهايات",
    textareaPlaceholder: "اكتب أسماء الدروس هنا...",
    verifyAndGenerate: "🔍 التحقق وإنشاء الفرض",
    generatedAssessment: "الفرض المولد",
    showCorrection: "إظهار الإصلاح",
    modelCorrection: "الإصلاح النموذجي",
    backToAssessment: "⬅️ العودة للفرض",
    assessmentType: "تصنيف التقييم الرسمي",
    assessmentNumber: "رقم التقييم المعتمد",
    examsTitle: "نماذج: ",
    openPdf: "فتح PDF فوري",
    noPdf: "لا توجد نسخ رقمية رسمية متاحة حالياً لهذا الفرض.",
    lessonList: "قائمة الدروس والكتب",
    viewLesson: "عرض الدرس (PDF)",
    askExplanation: "💬 اطلب شرحاً",
    lessonTitle: "درس: ",
    whatToKnow: "ماذا تريد أن تعرف عن هذا الدرس؟",
    queryPlaceholder: "اكتب سؤالك هنا بالتفصيل...",
    startInteractiveExplanation: "ابدأ الشرح التفاعلي",
    lessonExplanation: "شرح الدرس: ",
    askAnotherQuestion: "طرح سؤال آخر حول هذا الدرس",
    pdfNotSupported: "جهازك لا يدعم عرض الـ PDF مباشرة داخل التطبيق.",
    openExternal: "فتح في قارئ خارجي",
    close: "إغلاق",
    print: "طباعة",
    error429: "عذراً، تم تجاوز حد الطلبات المسموح به حالياً. يرجى الانتظار دقيقة ثم المحاولة مرة أخرى.",
    error500: "عذراً، هناك مشكلة مؤقتة في الاتصال بالخادم. يرجى المحاولة مرة أخرى.",
    errorUnexpected: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى لاحقاً.",
    invalidLessons: "عذراً، الدروس التالية غير موجودة في البرنامج الرسمي لهذه المادة: ",
    correctLessonNames: "يرجى تصحيح أسماء الدروس.",
    writeCorrectLessons: "يرجى كتابة أسماء دروس صحيحة.",
    availableExams: "⚠️ متاح حالياً {count} نماذج رسمية فقط لهذا التصنيف.",
    followGeneralStream: "المتابعة (شعبة عامة)",
    generalStream: "عام"
  },
  fr: {
    back: "Retour",
    next: "Suivant",
    loading: "Extraction des données officielles du ministère...",
    chooseLanguage: "Choisissez la langue de l'interface",
    chooseCountry: "Choisissez votre pays",
    chooseGrade: "Année scolaire officielle",
    chooseStream: "Filière ou spécialité approuvée",
    chooseSubject: "Matières scolaires prescrites",
    lessonsAndBooks: "Leçons et Livres",
    officialCurriculum: "Programmes officiels approuvés",
    examsAndAssessments: "Examens et Devoirs",
    previousExams: "Modèles officiels des années précédentes",
    generateAssessment: "Générer un devoir (Interactif)",
    generateAssessmentDesc: "Générer un devoir personnalisé selon vos leçons",
    officialExams: "Examens Officiels",
    officialExamsDesc: "Modèles officiels des années précédentes (PDF)",
    writeLessons: "Écrivez les leçons concernées par le devoir",
    lessonsPlaceholder: "Vous pouvez écrire le nom d'une ou plusieurs leçons séparées par une virgule",
    exampleLessons: "Exemple : Dérivation, Fonction exponentielle, Limites",
    textareaPlaceholder: "Écrivez les noms des leçons ici...",
    verifyAndGenerate: "🔍 Vérifier et générer le devoir",
    generatedAssessment: "Devoir généré",
    showCorrection: "Afficher la correction",
    modelCorrection: "Correction type",
    backToAssessment: "⬅️ Retour au devoir",
    assessmentType: "Classification de l'évaluation officielle",
    assessmentNumber: "Numéro d'évaluation approuvé",
    examsTitle: "Modèles : ",
    openPdf: "Ouvrir PDF immédiatement",
    noPdf: "Aucune version numérique officielle n'est actuellement disponible pour ce devoir.",
    lessonList: "Liste des leçons et livres",
    viewLesson: "Voir la leçon (PDF)",
    askExplanation: "💬 Demander une explication",
    lessonTitle: "Leçon : ",
    whatToKnow: "Que voulez-vous savoir sur cette leçon ?",
    queryPlaceholder: "Écrivez votre question ici en détail...",
    startInteractiveExplanation: "Commencer l'explication interactive",
    lessonExplanation: "Explication de la leçon : ",
    askAnotherQuestion: "Poser une autre question sur cette leçon",
    pdfNotSupported: "Votre appareil ne supporte pas l'affichage direct du PDF dans l'application.",
    openExternal: "Ouvrir dans un lecteur externe",
    close: "Fermer",
    print: "Imprimer",
    error429: "Désolé, la limite de requêtes autorisée a été dépassée. Veuillez attendre une minute puis réessayer.",
    error500: "Désolé, il y a un problème temporaire de connexion au serveur. Veuillez réessayer.",
    errorUnexpected: "Une erreur inattendue s'est produite. Veuillez réessayer plus tard.",
    invalidLessons: "Désolé, les leçons suivantes ne figurent pas dans le programme officiel de cette matière : ",
    correctLessonNames: "Veuillez corriger les noms des leçons.",
    writeCorrectLessons: "Veuillez écrire des noms de leçons corrects.",
    availableExams: "⚠️ Actuellement, seuls {count} modèles officiels sont disponibles pour cette catégorie.",
    followGeneralStream: "Continuer (Filière générale)",
    generalStream: "Général"
  },
  en: {
    back: "Back",
    next: "Next",
    loading: "Extracting official data from the Ministry...",
    chooseLanguage: "Choose Interface Language",
    chooseCountry: "Choose your country",
    chooseGrade: "Official School Year",
    chooseStream: "Approved Stream or Specialty",
    chooseSubject: "Prescribed School Subjects",
    lessonsAndBooks: "Lessons and Books",
    officialCurriculum: "Approved Official Curricula",
    examsAndAssessments: "Exams and Assessments",
    previousExams: "Official models from previous years",
    generateAssessment: "Generate Assessment (Interactive)",
    generateAssessmentDesc: "Generate a custom assessment based on your lessons",
    officialExams: "Official Exams",
    officialExamsDesc: "Official models from previous years (PDF)",
    writeLessons: "Write the lessons covered by the assessment",
    lessonsPlaceholder: "You can write the name of one or more lessons separated by a comma",
    exampleLessons: "Example: Differentiation, Exponential Function, Limits",
    textareaPlaceholder: "Write lesson names here...",
    verifyAndGenerate: "🔍 Verify and Generate Assessment",
    generatedAssessment: "Generated Assessment",
    showCorrection: "Show Correction",
    modelCorrection: "Model Correction",
    backToAssessment: "⬅️ Back to Assessment",
    assessmentType: "Official Evaluation Classification",
    assessmentNumber: "Approved Evaluation Number",
    examsTitle: "Models: ",
    openPdf: "Open PDF instantly",
    noPdf: "No official digital versions are currently available for this assessment.",
    lessonList: "List of lessons and books",
    viewLesson: "View Lesson (PDF)",
    askExplanation: "💬 Ask for an explanation",
    lessonTitle: "Lesson: ",
    whatToKnow: "What do you want to know about this lesson?",
    queryPlaceholder: "Write your question here in detail...",
    startInteractiveExplanation: "Start Interactive Explanation",
    lessonExplanation: "Lesson Explanation: ",
    askAnotherQuestion: "Ask another question about this lesson",
    pdfNotSupported: "Your device does not support direct PDF viewing within the app.",
    openExternal: "Open in external reader",
    close: "Close",
    print: "Print",
    error429: "Sorry, the current request limit has been exceeded. Please wait a minute and try again.",
    error500: "Sorry, there is a temporary server connection problem. Please try again.",
    errorUnexpected: "An unexpected error occurred. Please try again later.",
    invalidLessons: "Sorry, the following lessons are not in the official program for this subject: ",
    correctLessonNames: "Please correct the lesson names.",
    writeCorrectLessons: "Please write correct lesson names.",
    availableExams: "⚠️ Currently, only {count} official models are available for this category.",
    followGeneralStream: "Continue (General Stream)",
    generalStream: "General"
  }
};

export const COUNTRIES: Country[] = [
  { id: 'sa', names: { ar: 'السعودية', fr: 'Arabie Saoudite', en: 'Saudi Arabia' }, flag: '🇸🇦', ministryUrl: 'moe.gov.sa' },
  { id: 'eg', names: { ar: 'مصر', fr: 'Égypte', en: 'Egypt' }, flag: '🇪🇬', ministryUrl: 'moe.gov.eg' },
  { id: 'dz', names: { ar: 'الجزائر', fr: 'Algérie', en: 'Algeria' }, flag: '🇩🇿', ministryUrl: 'education.gov.dz' },
  { id: 'ma', names: { ar: 'المغرب', fr: 'Maroc', en: 'Morocco' }, flag: '🇲🇦', ministryUrl: 'men.gov.ma' },
  { id: 'iq', names: { ar: 'العراق', fr: 'Irak', en: 'Iraq' }, flag: '🇮🇶', ministryUrl: 'moedu.gov.iq' },
  { id: 'jo', names: { ar: 'الأردن', fr: 'Jordanie', en: 'Jordan' }, flag: '🇯🇴', ministryUrl: 'moe.gov.jo' },
  { id: 'ps', names: { ar: 'فلسطين', fr: 'Palestine', en: 'Palestine' }, flag: '🇵🇸', ministryUrl: 'moe.pna.ps' },
  { id: 'sy', names: { ar: 'سوريا', fr: 'Syrie', en: 'Syria' }, flag: '🇸🇾', ministryUrl: 'moed.gov.sy' },
  { id: 'lb', names: { ar: 'لبنان', fr: 'Liban', en: 'Lebanon' }, flag: '🇱🇧', ministryUrl: 'mehe.gov.lb' },
  { id: 'ae', names: { ar: 'الإمارات', fr: 'Émirats Arabes Unis', en: 'United Arab Emirates' }, flag: '🇦🇪', ministryUrl: 'moe.gov.ae' },
  { id: 'kw', names: { ar: 'الكويت', fr: 'Koweït', en: 'Kuwait' }, flag: '🇰🇼', ministryUrl: 'moe.edu.kw' },
  { id: 'qa', names: { ar: 'قطر', fr: 'Qatar', en: 'Qatar' }, flag: '🇶🇦', ministryUrl: 'edu.gov.qa' },
  { id: 'om', names: { ar: 'عمان', fr: 'Oman', en: 'Oman' }, flag: '🇴🇲', ministryUrl: 'moe.gov.om' },
  { id: 'bh', names: { ar: 'البحرين', fr: 'Bahreïn', en: 'Bahrain' }, flag: '🇧🇭', ministryUrl: 'moe.gov.bh' },
  { id: 'ye', names: { ar: 'اليمن', fr: 'Yémen', en: 'Yemen' }, flag: '🇾🇪', ministryUrl: 'moe-ye.net' },
  { id: 'tn', names: { ar: 'تونس', fr: 'Tunisie', en: 'Tunisia' }, flag: '🇹🇳', ministryUrl: 'education.gov.tn' },
  { id: 'ly', names: { ar: 'ليبيا', fr: 'Libye', en: 'Libya' }, flag: '🇱🇾', ministryUrl: 'moe.gov.ly' },
  { id: 'sd', names: { ar: 'السودان', fr: 'Soudan', en: 'Sudan' }, flag: '🇸🇩', ministryUrl: 'moe.gov.sd' },
  { id: 'mr', names: { ar: 'موريتانيا', fr: 'Mauritanie', en: 'Mauritania' }, flag: '🇲🇷', ministryUrl: 'education.gov.mr' },
  { id: 'so', names: { ar: 'الصومال', fr: 'Somalie', en: 'Somalia' }, flag: '🇸🇴', ministryUrl: 'moe.gov.so' },
  { id: 'dj', names: { ar: 'جيبوتي', fr: 'Djibouti', en: 'Djibouti' }, flag: '🇩🇯', ministryUrl: 'education.gouv.dj' },
  { id: 'km', names: { ar: 'جزر القمر', fr: 'Comores', en: 'Comoros' }, flag: '🇰🇲', ministryUrl: 'education.km' }
];
